# Generated by Django 5.1.6 on 2025-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_confirm', 'รออนุมัติ'), ('approved', 'กำลังดำเนินการ'), ('rejected', 'ปฏิเสธ'), ('completed', 'สำเร็จ')], default='waiting_confirm', max_length=20),
        ),
    ]
