# Generated by Django 5.1.6 on 2025-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_pickup_time_alter_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
