# Generated by Django 5.1.6 on 2025-03-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_pickup_end_time_order_pickup_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pickup_end_time',
            new_name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_start_time',
        ),
    ]
