# Generated by Django 5.1.6 on 2025-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
