# Generated by Django 5.1.6 on 2025-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'ลูกค้า'), ('staff', 'พนักงาน'), ('admin', 'แอดมิน')], default='customer', max_length=20),
        ),
    ]
